"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper TWA API.
 * REST API for Tonkeeper TWA.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.AccountEventsSubscriptionStatus200ResponseToJSON = exports.AccountEventsSubscriptionStatus200ResponseFromJSONTyped = exports.AccountEventsSubscriptionStatus200ResponseFromJSON = exports.instanceOfAccountEventsSubscriptionStatus200Response = void 0;
/**
 * Check if a given object implements the AccountEventsSubscriptionStatus200Response interface.
 */
function instanceOfAccountEventsSubscriptionStatus200Response(value) {
    var isInstance = true;
    isInstance = isInstance && "subscribed" in value;
    return isInstance;
}
exports.instanceOfAccountEventsSubscriptionStatus200Response = instanceOfAccountEventsSubscriptionStatus200Response;
function AccountEventsSubscriptionStatus200ResponseFromJSON(json) {
    return AccountEventsSubscriptionStatus200ResponseFromJSONTyped(json, false);
}
exports.AccountEventsSubscriptionStatus200ResponseFromJSON = AccountEventsSubscriptionStatus200ResponseFromJSON;
function AccountEventsSubscriptionStatus200ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'subscribed': json['subscribed']
    };
}
exports.AccountEventsSubscriptionStatus200ResponseFromJSONTyped = AccountEventsSubscriptionStatus200ResponseFromJSONTyped;
function AccountEventsSubscriptionStatus200ResponseToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'subscribed': value.subscribed
    };
}
exports.AccountEventsSubscriptionStatus200ResponseToJSON = AccountEventsSubscriptionStatus200ResponseToJSON;
