"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper TWA API.
 * REST API for Tonkeeper TWA.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.AccountEventsSubscriptionStatusRequestToJSON = exports.AccountEventsSubscriptionStatusRequestFromJSONTyped = exports.AccountEventsSubscriptionStatusRequestFromJSON = exports.instanceOfAccountEventsSubscriptionStatusRequest = void 0;
/**
 * Check if a given object implements the AccountEventsSubscriptionStatusRequest interface.
 */
function instanceOfAccountEventsSubscriptionStatusRequest(value) {
    var isInstance = true;
    isInstance = isInstance && "twaInitData" in value;
    isInstance = isInstance && "address" in value;
    return isInstance;
}
exports.instanceOfAccountEventsSubscriptionStatusRequest = instanceOfAccountEventsSubscriptionStatusRequest;
function AccountEventsSubscriptionStatusRequestFromJSON(json) {
    return AccountEventsSubscriptionStatusRequestFromJSONTyped(json, false);
}
exports.AccountEventsSubscriptionStatusRequestFromJSON = AccountEventsSubscriptionStatusRequestFromJSON;
function AccountEventsSubscriptionStatusRequestFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'twaInitData': json['twa_init_data'],
        'address': json['address']
    };
}
exports.AccountEventsSubscriptionStatusRequestFromJSONTyped = AccountEventsSubscriptionStatusRequestFromJSONTyped;
function AccountEventsSubscriptionStatusRequestToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'twa_init_data': value.twaInitData,
        'address': value.address
    };
}
exports.AccountEventsSubscriptionStatusRequestToJSON = AccountEventsSubscriptionStatusRequestToJSON;
