"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper TWA API.
 * REST API for Tonkeeper TWA.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.BalanceToJSON = exports.BalanceFromJSONTyped = exports.BalanceFromJSON = exports.instanceOfBalance = void 0;
/**
 * Check if a given object implements the Balance interface.
 */
function instanceOfBalance(value) {
    var isInstance = true;
    isInstance = isInstance && "balance" in value;
    return isInstance;
}
exports.instanceOfBalance = instanceOfBalance;
function BalanceFromJSON(json) {
    return BalanceFromJSONTyped(json, false);
}
exports.BalanceFromJSON = BalanceFromJSON;
function BalanceFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'balance': json['balance']
    };
}
exports.BalanceFromJSONTyped = BalanceFromJSONTyped;
function BalanceToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'balance': value.balance
    };
}
exports.BalanceToJSON = BalanceToJSON;
