"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper TWA API.
 * REST API for Tonkeeper TWA.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.BridgeWebhookRequestToJSON = exports.BridgeWebhookRequestFromJSONTyped = exports.BridgeWebhookRequestFromJSON = exports.instanceOfBridgeWebhookRequest = void 0;
/**
 * Check if a given object implements the BridgeWebhookRequest interface.
 */
function instanceOfBridgeWebhookRequest(value) {
    var isInstance = true;
    isInstance = isInstance && "topic" in value;
    isInstance = isInstance && "hash" in value;
    return isInstance;
}
exports.instanceOfBridgeWebhookRequest = instanceOfBridgeWebhookRequest;
function BridgeWebhookRequestFromJSON(json) {
    return BridgeWebhookRequestFromJSONTyped(json, false);
}
exports.BridgeWebhookRequestFromJSON = BridgeWebhookRequestFromJSON;
function BridgeWebhookRequestFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'topic': json['topic'],
        'hash': json['hash']
    };
}
exports.BridgeWebhookRequestFromJSONTyped = BridgeWebhookRequestFromJSONTyped;
function BridgeWebhookRequestToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'topic': value.topic,
        'hash': value.hash
    };
}
exports.BridgeWebhookRequestToJSON = BridgeWebhookRequestToJSON;
