"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper TWA API.
 * REST API for Tonkeeper TWA.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.GetTonConnectPayloadDefaultResponseToJSON = exports.GetTonConnectPayloadDefaultResponseFromJSONTyped = exports.GetTonConnectPayloadDefaultResponseFromJSON = exports.instanceOfGetTonConnectPayloadDefaultResponse = void 0;
/**
 * Check if a given object implements the GetTonConnectPayloadDefaultResponse interface.
 */
function instanceOfGetTonConnectPayloadDefaultResponse(value) {
    var isInstance = true;
    isInstance = isInstance && "error" in value;
    return isInstance;
}
exports.instanceOfGetTonConnectPayloadDefaultResponse = instanceOfGetTonConnectPayloadDefaultResponse;
function GetTonConnectPayloadDefaultResponseFromJSON(json) {
    return GetTonConnectPayloadDefaultResponseFromJSONTyped(json, false);
}
exports.GetTonConnectPayloadDefaultResponseFromJSON = GetTonConnectPayloadDefaultResponseFromJSON;
function GetTonConnectPayloadDefaultResponseFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'error': json['error']
    };
}
exports.GetTonConnectPayloadDefaultResponseFromJSONTyped = GetTonConnectPayloadDefaultResponseFromJSONTyped;
function GetTonConnectPayloadDefaultResponseToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'error': value.error
    };
}
exports.GetTonConnectPayloadDefaultResponseToJSON = GetTonConnectPayloadDefaultResponseToJSON;
