"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper TWA API.
 * REST API for Tonkeeper TWA.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.SubscribeToBridgeEventsRequestToJSON = exports.SubscribeToBridgeEventsRequestFromJSONTyped = exports.SubscribeToBridgeEventsRequestFromJSON = exports.instanceOfSubscribeToBridgeEventsRequest = void 0;
/**
 * Check if a given object implements the SubscribeToBridgeEventsRequest interface.
 */
function instanceOfSubscribeToBridgeEventsRequest(value) {
    var isInstance = true;
    isInstance = isInstance && "twaInitData" in value;
    isInstance = isInstance && "clientId" in value;
    isInstance = isInstance && "origin" in value;
    return isInstance;
}
exports.instanceOfSubscribeToBridgeEventsRequest = instanceOfSubscribeToBridgeEventsRequest;
function SubscribeToBridgeEventsRequestFromJSON(json) {
    return SubscribeToBridgeEventsRequestFromJSONTyped(json, false);
}
exports.SubscribeToBridgeEventsRequestFromJSON = SubscribeToBridgeEventsRequestFromJSON;
function SubscribeToBridgeEventsRequestFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'twaInitData': json['twa_init_data'],
        'clientId': json['client_id'],
        'origin': json['origin']
    };
}
exports.SubscribeToBridgeEventsRequestFromJSONTyped = SubscribeToBridgeEventsRequestFromJSONTyped;
function SubscribeToBridgeEventsRequestToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'twa_init_data': value.twaInitData,
        'client_id': value.clientId,
        'origin': value.origin
    };
}
exports.SubscribeToBridgeEventsRequestToJSON = SubscribeToBridgeEventsRequestToJSON;
