"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper TWA API.
 * REST API for Tonkeeper TWA.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.SubscribeToAccountEventsRequestToJSON = exports.SubscribeToAccountEventsRequestFromJSONTyped = exports.SubscribeToAccountEventsRequestFromJSON = exports.instanceOfSubscribeToAccountEventsRequest = void 0;
var SubscribeToAccountEventsRequestProof_1 = require("./SubscribeToAccountEventsRequestProof");
/**
 * Check if a given object implements the SubscribeToAccountEventsRequest interface.
 */
function instanceOfSubscribeToAccountEventsRequest(value) {
    var isInstance = true;
    isInstance = isInstance && "twaInitData" in value;
    isInstance = isInstance && "address" in value;
    isInstance = isInstance && "proof" in value;
    return isInstance;
}
exports.instanceOfSubscribeToAccountEventsRequest = instanceOfSubscribeToAccountEventsRequest;
function SubscribeToAccountEventsRequestFromJSON(json) {
    return SubscribeToAccountEventsRequestFromJSONTyped(json, false);
}
exports.SubscribeToAccountEventsRequestFromJSON = SubscribeToAccountEventsRequestFromJSON;
function SubscribeToAccountEventsRequestFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'twaInitData': json['twa_init_data'],
        'address': json['address'],
        'proof': (0, SubscribeToAccountEventsRequestProof_1.SubscribeToAccountEventsRequestProofFromJSON)(json['proof'])
    };
}
exports.SubscribeToAccountEventsRequestFromJSONTyped = SubscribeToAccountEventsRequestFromJSONTyped;
function SubscribeToAccountEventsRequestToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'twa_init_data': value.twaInitData,
        'address': value.address,
        'proof': (0, SubscribeToAccountEventsRequestProof_1.SubscribeToAccountEventsRequestProofToJSON)(value.proof)
    };
}
exports.SubscribeToAccountEventsRequestToJSON = SubscribeToAccountEventsRequestToJSON;
