"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper TWA API.
 * REST API for Tonkeeper TWA.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.SubscribeToAccountEventsRequestProofToJSON = exports.SubscribeToAccountEventsRequestProofFromJSONTyped = exports.SubscribeToAccountEventsRequestProofFromJSON = exports.instanceOfSubscribeToAccountEventsRequestProof = void 0;
var runtime_1 = require("../runtime");
var SubscribeToAccountEventsRequestProofDomain_1 = require("./SubscribeToAccountEventsRequestProofDomain");
/**
 * Check if a given object implements the SubscribeToAccountEventsRequestProof interface.
 */
function instanceOfSubscribeToAccountEventsRequestProof(value) {
    var isInstance = true;
    isInstance = isInstance && "timestamp" in value;
    isInstance = isInstance && "domain" in value;
    isInstance = isInstance && "signature" in value;
    isInstance = isInstance && "payload" in value;
    return isInstance;
}
exports.instanceOfSubscribeToAccountEventsRequestProof = instanceOfSubscribeToAccountEventsRequestProof;
function SubscribeToAccountEventsRequestProofFromJSON(json) {
    return SubscribeToAccountEventsRequestProofFromJSONTyped(json, false);
}
exports.SubscribeToAccountEventsRequestProofFromJSON = SubscribeToAccountEventsRequestProofFromJSON;
function SubscribeToAccountEventsRequestProofFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'timestamp': json['timestamp'],
        'domain': (0, SubscribeToAccountEventsRequestProofDomain_1.SubscribeToAccountEventsRequestProofDomainFromJSON)(json['domain']),
        'signature': json['signature'],
        'payload': json['payload'],
        'stateInit': !(0, runtime_1.exists)(json, 'state_init') ? undefined : json['state_init']
    };
}
exports.SubscribeToAccountEventsRequestProofFromJSONTyped = SubscribeToAccountEventsRequestProofFromJSONTyped;
function SubscribeToAccountEventsRequestProofToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'timestamp': value.timestamp,
        'domain': (0, SubscribeToAccountEventsRequestProofDomain_1.SubscribeToAccountEventsRequestProofDomainToJSON)(value.domain),
        'signature': value.signature,
        'payload': value.payload,
        'state_init': value.stateInit
    };
}
exports.SubscribeToAccountEventsRequestProofToJSON = SubscribeToAccountEventsRequestProofToJSON;
