"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper TWA API.
 * REST API for Tonkeeper TWA.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.SubscribeToAccountEventsRequestProofDomainToJSON = exports.SubscribeToAccountEventsRequestProofDomainFromJSONTyped = exports.SubscribeToAccountEventsRequestProofDomainFromJSON = exports.instanceOfSubscribeToAccountEventsRequestProofDomain = void 0;
var runtime_1 = require("../runtime");
/**
 * Check if a given object implements the SubscribeToAccountEventsRequestProofDomain interface.
 */
function instanceOfSubscribeToAccountEventsRequestProofDomain(value) {
    var isInstance = true;
    isInstance = isInstance && "value" in value;
    return isInstance;
}
exports.instanceOfSubscribeToAccountEventsRequestProofDomain = instanceOfSubscribeToAccountEventsRequestProofDomain;
function SubscribeToAccountEventsRequestProofDomainFromJSON(json) {
    return SubscribeToAccountEventsRequestProofDomainFromJSONTyped(json, false);
}
exports.SubscribeToAccountEventsRequestProofDomainFromJSON = SubscribeToAccountEventsRequestProofDomainFromJSON;
function SubscribeToAccountEventsRequestProofDomainFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'lengthBytes': !(0, runtime_1.exists)(json, 'length_bytes') ? undefined : json['length_bytes'],
        'value': json['value']
    };
}
exports.SubscribeToAccountEventsRequestProofDomainFromJSONTyped = SubscribeToAccountEventsRequestProofDomainFromJSONTyped;
function SubscribeToAccountEventsRequestProofDomainToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'length_bytes': value.lengthBytes,
        'value': value.value
    };
}
exports.SubscribeToAccountEventsRequestProofDomainToJSON = SubscribeToAccountEventsRequestProofDomainToJSON;
