"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper TWA API.
 * REST API for Tonkeeper TWA.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.UnsubscribeFromBridgeEventsRequestToJSON = exports.UnsubscribeFromBridgeEventsRequestFromJSONTyped = exports.UnsubscribeFromBridgeEventsRequestFromJSON = exports.instanceOfUnsubscribeFromBridgeEventsRequest = void 0;
var runtime_1 = require("../runtime");
/**
 * Check if a given object implements the UnsubscribeFromBridgeEventsRequest interface.
 */
function instanceOfUnsubscribeFromBridgeEventsRequest(value) {
    var isInstance = true;
    isInstance = isInstance && "twaInitData" in value;
    return isInstance;
}
exports.instanceOfUnsubscribeFromBridgeEventsRequest = instanceOfUnsubscribeFromBridgeEventsRequest;
function UnsubscribeFromBridgeEventsRequestFromJSON(json) {
    return UnsubscribeFromBridgeEventsRequestFromJSONTyped(json, false);
}
exports.UnsubscribeFromBridgeEventsRequestFromJSON = UnsubscribeFromBridgeEventsRequestFromJSON;
function UnsubscribeFromBridgeEventsRequestFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'twaInitData': json['twa_init_data'],
        'clientId': !(0, runtime_1.exists)(json, 'client_id') ? undefined : json['client_id']
    };
}
exports.UnsubscribeFromBridgeEventsRequestFromJSONTyped = UnsubscribeFromBridgeEventsRequestFromJSONTyped;
function UnsubscribeFromBridgeEventsRequestToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'twa_init_data': value.twaInitData,
        'client_id': value.clientId
    };
}
exports.UnsubscribeFromBridgeEventsRequestToJSON = UnsubscribeFromBridgeEventsRequestToJSON;
