"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper TWA API.
 * REST API for Tonkeeper TWA.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.UnsubscribeFromAccountEventsRequestToJSON = exports.UnsubscribeFromAccountEventsRequestFromJSONTyped = exports.UnsubscribeFromAccountEventsRequestFromJSON = exports.instanceOfUnsubscribeFromAccountEventsRequest = void 0;
/**
 * Check if a given object implements the UnsubscribeFromAccountEventsRequest interface.
 */
function instanceOfUnsubscribeFromAccountEventsRequest(value) {
    var isInstance = true;
    isInstance = isInstance && "twaInitData" in value;
    return isInstance;
}
exports.instanceOfUnsubscribeFromAccountEventsRequest = instanceOfUnsubscribeFromAccountEventsRequest;
function UnsubscribeFromAccountEventsRequestFromJSON(json) {
    return UnsubscribeFromAccountEventsRequestFromJSONTyped(json, false);
}
exports.UnsubscribeFromAccountEventsRequestFromJSON = UnsubscribeFromAccountEventsRequestFromJSON;
function UnsubscribeFromAccountEventsRequestFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'twaInitData': json['twa_init_data']
    };
}
exports.UnsubscribeFromAccountEventsRequestFromJSONTyped = UnsubscribeFromAccountEventsRequestFromJSONTyped;
function UnsubscribeFromAccountEventsRequestToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'twa_init_data': value.twaInitData
    };
}
exports.UnsubscribeFromAccountEventsRequestToJSON = UnsubscribeFromAccountEventsRequestToJSON;
